Adding the fix for the journal collection at the skip of journal pretty
Issue we have observed is that at the journal pretty skip
we want to collect the journal normal logs but it was not
happening.

Fix we have provided is that the status for the journal command
was not handled properly so fixed it.

Test we have done by manually changing the return code for the
function to capture the error scenario.

Fixes nvbug https://nvbugspro.nvidia.com/bug/5078587
Signed-off-by: Deepak Kamat <dkamat@nvidia.com>

diff --git a/tools/dreport.d/plugins.d/journalpretty b/tools/dreport.d/plugins.d/journalpretty
--- a/tools/dreport.d/plugins.d/journalpretty
+++ b/tools/dreport.d/plugins.d/journalpretty
@@ -11,14 +11,15 @@ file_name="journal-pretty.log"
 command="journalctl -o json-pretty"
 
 add_cmd_output "$command" "$file_name" "$desc"
+status=$?  # Capture exit status of journalctl
 
-if [ $? -eq 1 ]; then
+if [ $status -eq 1 ]; then
     desc="Journal log at error"
     file_name="journal-pretty-error.log"
     command_compact="journalctl || true"
     add_cmd_output "$command_compact" "$file_name" "$desc"
 
-elif [ $? -eq 2 ]; then
+elif [ $status -eq 2 ]; then
     desc="Journal log"
     file_name="journal.log"
     command_compact="journalctl"
